### ISSUE TITLE
help

### ISSUE THREAD

**Issue by fpxno1** [sandialabs/NuMAD#18]
could you tell me how to transform the blade.nmd model into ansys FEM model,I am a graduate student majoing in mechanical engineering

**Comment by rclarke17** [comment]
There are two ways to generate an ANSYS model from an .nmd file. If you have a blade object generated that corresponds to your .nmd blade you can use the new NuMAD v3 way using the command:

layupDesign_ANSYSmesh(blade, 'name of your .nmd file goes here')

For an example of this look at the ExcelToObject folder in examples.

The old NuMAD v2 way to generate an ANSYS model from an .nmd file is to open the .nmd file in the NuMAD GUI, to access the GUI type numad into Matlabs command line after adding the Numad paths using the command addNumadPaths, then once you are in the GUI go file-> open model and select your .nmd file, once you have loaded in your .nmd file you can go to ANSYS in the tool bar and select Generate Now to build an ANSYS model.

**Comment by omaudhuit** [comment]
@rclarke17 0 - Hope all is well. Was wondering if I could get some help on some errors I am getting when running the excel2NumadObject.m script. 

I can't seem to be able to generate the mesh. 

![Excel2NumadObject](https://user-images.githubusercontent.com/50264211/193107915-acd96943-6a4e-45e6-a006-b2842e444271.PNG)

**Comment by rclarke17** [comment]
Try replacing line 19 with this:
BladeDef_to_NuMADfile(blade,NuMADfile,'MatDBsi.txt', strcat(pwd, '\airfoils'));

**Comment by omaudhuit** [comment]
@rclarke17 - Thank you very much for the response. 

Trying to get more familiar NuMAD since we have mainly been working with FAST but would like to start gaining a deeper understanding on the structural side. 

Could you share some insight into the mesh generation - is this contained within the .src file that is outputted from the above script? The readthedocs for v3.0 doesn't go into so much detail regarding how ANSYS is interfaced. 

Any feedback would be much appreciated.

**Comment by rclarke17** [comment]
My guess is that the number of nodes and elements it is trying to make exceeds the allowable limit of ANSYS student version. 
one thing you could try is using a coarser mesh, by setting blade.mesh in the Excel2NumadObject.m script to 0.5, this will make a very poor mesh but it's just a check of if that is the issue. 

As for your question of how NuMAD interfaces with ANSYS, it is through the shell7.src script, essentially NuMAD translates the geometry data of the wind blade into ANSYS APDL batch language that are then written to the shell7 script, we then rely on ANSYS to mesh the geometry for us.

One of our development tasks that we at Sandia are working on right now is to decouple blade mesh creation from ANSYS, essentially we are creating an in-house mesher for NuMAD so that any FEA program can then be used to analyze your blade.

**Comment by omaudhuit** [comment]
@rclarke17 - Thanks again for the feedback and the information.

The Ansys student version may be the cause. I've even tried reading the SNL61p5m_NuMAD_121212 reference model .src file directly in ADPL but have come across a series of errors (with the program crashing entirely at times):

![Shell7src_AnsysAPDL](https://user-images.githubusercontent.com/50264211/193615266-7cc8f6e3-54c0-4887-91e9-7a9908b4b6d9.PNG)

If you have ever come across such behavior do let me know. 

I will have to look into acquiring another Ansys license.

**Comment by fpxno1** [comment]
whether the numad 3.0 has more specifical explanation,I want to learn more about it

**Comment by omaudhuit** [comment]
@fpxno1 - Not sure if this is what you are looking for but I would definitely start with the available documentation: https://numad.readthedocs.io/en/latest/user/fea.html

**Comment by fpxno1** [comment]
> @fpxno1 - Not sure if this is what you are looking for but I would definitely start with the available documentation: https://numad.readthedocs.io/en/latest/user/fea.html

thank you bro,I have found that,and I successfully run those examples,but i don't know how to use NUMAD according to need,I am a student exploring the wind turbine blade area without tutor's guidance ,It is too difficult, wish to  communicate more.

**Comment by omaudhuit** [comment]
> @rclarke17 - Thanks again for the feedback and the information.
> 
> The Ansys student version may be the cause. I've even tried reading the SNL61p5m_NuMAD_121212 reference model .src file directly in ADPL but have come across a series of errors (with the program crashing entirely at times):
> 
> ![Shell7src_AnsysAPDL](https://user-images.githubusercontent.com/50264211/193615266-7cc8f6e3-54c0-4887-91e9-7a9908b4b6d9.PNG)
> 
> If you have ever come across such behavior do let me know.
> 
> I will have to look into acquiring another Ansys license.


@rclarke17 - Following up on this to see whether or not you or a colleague of yours have ever come across any issues even with the shell.src file from the reference model. Any response will be helpful. Thank you.

**Comment by ecamare** [comment]
Th ANSYS error "An element referred to as 91 ..."  occurs because newer versions of ANSYS discontinued the SHELL91 element. We have fixed this problem and are closing this issue. Please let us know if you still need help.

**Comment by veliemresavas** [comment]
> Th ANSYS error "An element referred to as 91 ..." occurs because newer versions of ANSYS discontinued the SHELL91 element. We have fixed this problem and are closing this issue. Please let us know if you still need help.

I do still encounter this issue while using the src in apdl?

**Comment by yunzhiliuliu** [comment]
Just my observation: I tried using GUI (open .nmd file) to run the example ExcelToObject. The generated .src file still has shell element 99 and 91 before line57. 

![Image](https://github.com/user-attachments/assets/ca687a2d-b9bb-406c-aaad-d84f0a5b82b6)

![Image](https://github.com/user-attachments/assets/f582e5c9-c720-482b-8b09-193d9841de86)

> Th ANSYS error "An element referred to as 91 ..." occurs because newer versions of ANSYS discontinued the SHELL91 element. We have fixed this problem and are closing this issue. Please let us know if you still need help.

**Comment by lee91628391029** [comment]
> ANSYS错误“一个被称为91的元素......”发生在新版本的ANSYS中停止了SHELL91元素。我们已经修复了这个问题，并准备关闭。如果你还需要帮助，请告诉我们。

Hi, the problem still persists when I import the .src file into ANSYS. Th ANSYS error "An element referred to as 91 ..."
